### ISSUE TITLE
Functional Requirements

### ISSUE THREAD

**Issue by marcusgeorgievski** [marcusgeorgievski/prj-team-1#15]
What the system **must do** and the services it provides for its users. It is important to keep this up to date into the design phase and prioritize order. 

> Avoid scope creep by thoroughly investigating and analyzing the features our users will like.

**Comment by lctoye** [comment]
Added 11 preliminary functional requirements to the SRS document in Week 4 deliverable folder. Please review, add and modify as needed.

**Comment by lctoye** [comment]
Reopening this issue while we are revising the Functional Requirements. The general principle behind the revision is summarized in this feedback:

> Overall this is a very high-level and does not spell out all the requirements. Need to elaborate more on this whole section.

For more specific details, please see the Feedback document inside the Week 4 Deliverables folder on MS Teams.
