### ISSUE TITLE
Prototype - UI/ UXD

### ISSUE THREAD

**Issue by Dmanoj07** [marcusgeorgievski/prj-team-1#24]
Mockups of user interface for the student management platform. Use wireframe.cc or similar tools.

**Comment by lctoye** [comment]
We will most likely need the following at minimum:

- [x] Registration & Login Page
- [x] Dashboard
- [x] Note-Taking Interface
- [x] Calendar
- [x] Deadline Manager

**Comment by lctoye** [comment]
Login/Registration: https://wireframe.cc/mqudFu

**Comment by marcusgeorgievski** [comment]
Just added some wireframes for the Dashboard, Calendar, and Deadline Manager.

**Comment by NoneNeko** [comment]
Reopen issues from the feedback as following
> This need to be revisited as the screens need to include clearly the data and the information the user will view/use/interact with at this time the screen does not show this either the exception of the login and creating an account

**Comment by marcusgeorgievski** [comment]
I've redone the UI mockups to more accurately represent our functional requirements. I used figma to create a realistic mockup that will make coding the front end easier and faster.
