### ISSUE TITLE
Activity Diagram

### ISSUE THREAD

**Issue by Dmanoj07** [marcusgeorgievski/prj-team-1#26]

**Comment by lctoye** [comment]
Added activity diagrams for:

- Account Registration
- Create & Save Note
- View & Edit Note

**Comment by NoneNeko** [comment]
Added activity diagrams for: 
Log In
Add schedule

**Comment by NoneNeko** [comment]
Reopen issues from the feedback as following

> The diagrams are missing many of the requirements listed in the functional requirements section. Please review and ipodate accordingly

**Comment by marcusgeorgievski** [comment]
I've complete my activity diagrams for creating classes.

- User can manually create a class
- User can upload a file. Our Azure AI service will extract and format the data to identify the class details and auto create assessments

**Comment by NoneNeko** [comment]
Update the Activity diagram for :
Create Assessment
Edit Assessment
Remove Assessment
Filter Assessment
Archive Assessment
Search

**Comment by lctoye** [comment]
Updated activity diagram & use case descriptions for Register & Login.
Created activity diagram, use case diagram and use case description for Dashboard.
