### ISSUE TITLE
3.2 Business Rules

### ISSUE THREAD

**Issue by NoneNeko** [marcusgeorgievski/prj-team-1#27]

**Comment by NoneNeko** [comment]
Reopen issues due to updates in functional requirements and activity diagram

**Comment by marcusgeorgievski** [comment]
I added for 11 business rules for my use cases on creating a class manually and with AI

**Comment by NoneNeko** [comment]
Added and Re-arranged the number for some business rules and changed the UC number accordingly.
Include: 
BR04 changed to be just students must log in to be used between UC 04-10.
BR06 changed from UC 11 to UC13 to match with the order
Added BR07 and 08 for UC 05, UC 06
Change some BR name in UC 12 to match with the one in 3.2 Business rules.
UC for creating class manually and with AI from UC0X to UC 11 and UC 12 respectively.
UC11 changed to UC13.
