### ISSUE TITLE
3.3 Use Case Specifications with corresponding interface mockups

### ISSUE THREAD

**Issue by NoneNeko** [marcusgeorgievski/prj-team-1#28]
Will have the following use case:
log in/register - Manoj
edit note - Manoj
edit schedule - Michael
upload and analyze addendum -Liam
create assignment -Marcus
create class - Marcus

**Comment by NoneNeko** [comment]
Reopen issues due to update in functional requirements and activity diagram.

**Comment by marcusgeorgievski** [comment]
Just finished my use cases and activity diagrams for the following:

- [x] - Create class manually
- [x] - Create class with AI

**Comment by Dmanoj07** [comment]
Updated my use cases and activity diagrams for the following:

 - Create Note,
 -Edit Note
 - Edit profile

**Comment by NoneNeko** [comment]
Update the Activity diagram, use case diagram, and use case description for :
- Create Assessment
- Edit Assessment
- Remove Assessment
- Filter Assessment
- Archive Assessment
- Search
