### ISSUE TITLE
Video Development

### ISSUE THREAD

**Issue by NoneNeko** [marcusgeorgievski/prj-team-1#30]
-Provide a demo of the system and its core functionality using scenarios using mock-up/wireframe screens.
- Slides should only contain the wireframe/mock-ups
- The team should create a script for each scenario to narrate from and use as a guide for the team

**Comment by lctoye** [comment]
Recorded my portion of the video which consisted of:
- Register
- Login 
- Dashboard

Details and file link are in the Teams chat.

**Comment by NoneNeko** [comment]
Adding recording for my part include:

- Assessment
- Add/edit assessment
- check all assessment
- search
