### ISSUE TITLE
Review and Update the SRS document

### ISSUE THREAD

**Issue by NoneNeko** [marcusgeorgievski/prj-team-1#31]
This includes the activity diagram, use case description, and business rules based on updated functional requirements.

**Comment by marcusgeorgievski** [comment]
The functional requirements have been updated. Terminology is now consistent and the requirements are well defined.

**Comment by Dmanoj07** [comment]
Update the Activity diagram, use case diagram and use case description for Create Note, Edit Note and Edit profile.

**Comment by NoneNeko** [comment]
Update the Activity diagram, use case diagram, and use case description for Create Assessment, Edit Assessment, Remove Assessment, Filter Assessment, Archive Assessment, and search.

**Comment by lctoye** [comment]
Updated activity diagram & use case descriptions for Register & Login.
Created activity diagram, use case diagram and use case description for Dashboard.
