### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by Dmanoj07** [marcusgeorgievski/prj-team-1#41]

**Comment by lctoye** [comment]
The product backlog is being laid out on this repository, with one milestone per sprint and each user story as an issue in its respective milestone.

Roadmap (please edit as needed):

### [Sprint 1](https://github.com/Dmanoj07/PRJ566_Team1/milestone/13)
- [x] Register (Liam)
    - #45 
- [x] Login (Liam)
    - #44 
- [x] Profile (Manoj)

### [Sprint 2](https://github.com/Dmanoj07/PRJ566_Team1/milestone/14)
- [x] Profile pt2 (Manoj)
- [x] Dashboard (Liam)
    - #46
- [x] Create Class (Marcus)

### [Sprint 3](https://github.com/Dmanoj07/PRJ566_Team1/milestone/15)
- [x] Create Class pt2 (Marcus)
- [x] Assessments (Michael)
- [x] Notes (Manoj)

### [Sprint 4](https://github.com/Dmanoj07/PRJ566_Team1/milestone/16)
- [x] AI Assessment (Marcus)
- [x] Notes pt2 (Marcus)
- [x] Search (Michael)

**Comment by marcusgeorgievski** [comment]
The user stories regarding classes are completed
