### ISSUE TITLE
As a user, I want to authenticate in order to access the system

### ISSUE THREAD

**Issue by lctoye** [marcusgeorgievski/prj-team-1#44]
### Description

We will develop an authentication system using JavaScript libraries for both front-end and back-end. The login form interface will be built with React and Next.js and will allow the user to enter their credentials. Upon submission of the login form, an HTTPS request will be sent to our back-end, which is built with Express. If the user credentials are correct, the user will gain access to the system and a session will be created to maintain that access. If the credentials are invalid, initiated to maintain their login state across the application, or be alerted that their login attempt was unsuccessful due to incorrect credentials.

### Acceptance Criteria

- Users must be able to sign into the system using credentials that adhere to the password policy.
- When invalid credentials are provided, an error message is displayed.
- Upon a successful authentication, users are redirected to the Dashboard module.
- User sessions remain active and secure throughout various pages.

### Testing Criteria

We will confirm the robustness of the authentication system by creating some test accounts in our PostgreSQL database. Testing will consist of login attempts with:

- Correct username; correct password (valid).
- Correct username; incorrect password (invalid).
- Incorrect usernames; correct password (invalid).

Testing should also ensure that unauthorized users cannot bypass the authentication system by directly visiting the relevant URLs without an active login session.

**Comment by marcusgeorgievski** [comment]
Clerk manages user sessions on the front end, no need for additional config.

For the backend, Clerk docs discuss implementing middleware in Express to authorize requests [here](https://clerk.com/docs/references/nodejs/overview).

We can close this issue once the middleware is implemented.
