### ISSUE TITLE
As a user, I want to create a note for my class.

### ISSUE THREAD

**Issue by Dmanoj07** [marcusgeorgievski/prj-team-1#48]
**Description**

we will develop a note-creating feature that allows users to compose and manage their notes. We will integrate a rich text editor into our application. This editor will provide users with a versatile interface for creating and formatting their notes. While users are actively editing their notes, we will temporarily cache their work. This ensures that their progress is not lost if they accidentally close the browser or navigate away from the page. After saving, the note will be stored permanently, and users will be redirected to a note dashboard.

**Acceptance Criteria**

-Users can format text (e.g., bold, italic) and add headings.
-Hyperlinks can be inserted within the editor.
- Images can be uploaded or embedded.
- While editing, if users accidentally close the browser or navigate away, their unsaved notes remain intact when they return.
- Saved notes are stored in our database

**Testing Criteria**

- Verify that the editor functions correctly (e.g., formatting, hyperlink insertion).
- Ensure compatibility across different browsers.
- Confirm that the editor handles different input scenarios.
- Validate that cached notes are retained upon returning to the application.
- Save test notes and verify their presence in the database.
- Confirm that redirection to the note dashboard occurs after saving.

**Comment by marcusgeorgievski** [comment]
complete. 7 hours later
