### ISSUE TITLE
As a user, I want to delete my profile

### ISSUE THREAD

**Issue by Dmanoj07** [marcusgeorgievski/prj-team-1#55]
we will implement a profile deletion feature. Users who wish to delete their account permanently can initiate this process. Users can navigate to their profile settings. Within the settings, there will be an option to delete the profile. Clicking this option will trigger the profile deletion process and redirect them to login/register page.

**Acceptance Criteria**

- The profile settings page includes a clear option for profile deletion.
- Users can easily locate and select this option.
- Upon selecting the deletion option, users will receive a confirmation prompt.
- Users must confirm their intent to proceed and it is irreversible.
- If confirmed, the system will permanently remove the user’s profile data from our database.
- After data removal, the user’s account will be inactivated and they will no longer have the access.

**Testing Criteria**

- Confirm that the delete option is functional.
- Trigger the deletion process and verify the clarity of the confirmation prompt.
- Confirm that users cannot proceed without confirming their intent.
- Inspect the database to ensure that the user’s data is no longer present.
- Attempt to log in using the user’s previous credentials.
- Confirm that access is denied.

**Comment by marcusgeorgievski** [comment]
Clerk provides an easy option to delete an account in the `Manage account` modal under the `Security tab`.

We need to implement a way to detect this and delete all their data - or do so after x amount of days.

Clerk has Webhooks for user deletion event. It seems we can only test it when the app is deployed. They provide the schema of the request so we can implement it before deploying.

**Comment by NoneNeko** [comment]
Move this from sprint 2 to sprint 1.
