### ISSUE TITLE
As a user, I want to be able to create a class to organize my notes and assessments in

### ISSUE THREAD

**Issue by marcusgeorgievski** [marcusgeorgievski/prj-team-1#56]
**Description**

As a user, I want to be able to create a class by specifying just the class name so that I can quickly add classes to the system.

**Acceptance Criteria**

- Users can enter the name of a class in a provided field.
- Upon submission, the class is added to the database with only the name specified.
- Users receive confirmation that the class has been successfully created.

**Testing Criteria**

- Test creating a class with valid class names.
- Test input validation to reject empty class names.
- Ensure that a confirmation message is displayed upon successful creation or error

**Comment by NoneNeko** [comment]
Move this from sprint 2 to sprint 1.
