### ISSUE TITLE
As a user, I want to be able to delete a class

### ISSUE THREAD

**Issue by marcusgeorgievski** [marcusgeorgievski/prj-team-1#57]
**Description**

As a user, I want to be able to delete a class so that I can remove classes that are no longer needed or created by mistake.

**Acceptance Criteria**

- Users can select the delete button from a classes menu options
- A confirmation prompt is displayed before the deletion is finalized
- Once confirmed, the class is removed from the database

**Testing Criteria**

- Test the deletion process with various classes
- Ensure the system requires user confirmation before deletion
- Confirm that deleted classes are no longer accessible in the system

**Comment by NoneNeko** [comment]
Move this from sprint 2 to sprint 1.

**Comment by Dmanoj07** [comment]
Added the functionality to delete class.
