### ISSUE TITLE
As a user, I want to be able to see all my classes so I can access them from a single source

### ISSUE THREAD

**Issue by marcusgeorgievski** [marcusgeorgievski/prj-team-1#61]
**Description**

As a user, I want to be able to see all my classes on the class page so that I can easily manage and access any class information.

**Acceptance Criteria**

- All classes associated with the user are displayed on the class page
- Each class entry shows relevant details such as the class name, professor, and any additional information
- The interface allows for easy navigation and management of class information

**Testing Criteria**

- Verify that all classes a user has created are listed
- Test the display of each piece of class information
- Check user interface for usability in managing classes

**Comment by NoneNeko** [comment]
Move this from sprint 2 to sprint 1.

**Comment by marcusgeorgievski** [comment]
The classes page is implemented
